global:
  imageProject: 1000jours

app:
  ~chart: app
  securityContext:
    fsGroup: 101
    runAsGroup: 101
    runAsUser: 101
  ingress:
    # adjustments for /zeroaccident path
    # proxy_upstream_name must be set to correct upstream
    # https://docs.unity3d.com/Manual/webgl-deploying.html
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Content-Security-Policy: default-src 'none'; connect-src 'self' https://*.gouv.fr; font-src 'self' data:; img-src 'self'; script-src 'self' https://*.gouv.fr 'unsafe-inline' 'unsafe-eval'; frame-src 'self' https://*.gouv.fr; style-src 'self' 'unsafe-inline'";
        more_set_headers "X-Frame-Options: sameorigin";
        more_set_headers "X-XSS-Protection: 1; mode=block";
        more_set_headers "X-Content-Type-Options: none";
        set $gz_type "";
        
        if ($request_uri ~* \.data\.gz$) {
          set $gz_type "application/octet-stream";
        }
        if ($request_uri ~* \.symbols\.json\.gz$) {
          set $gz_type "application/json";
        }
        if ($request_uri ~* \.js\.gz$) {
          set $gz_type "application/javascript";
        }
        if ($request_uri ~* \.wasm\.gz$) {
          set $gz_type "application/wasm";
        }

        if ($gz_type != "") {
          gzip off;
          more_set_headers "Content-Encoding: gzip";
          more_set_headers "Content-Type: $gz_type";
        }